### ISSUE TITLE
segmentation fault when using history on windows

### ISSUE THREAD

**Issue by sebsura** [xiaozhuai/readline-win32#1]
Something weird happens when i use this library on windows.  When i try to use the history feature (using ctrl+R on the console) my program just crashes.   I created a small reproducer here:

```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(readline REQUIRED IMPORTED_TARGET readline)
add_executable(rl-test rl_test.cc)
target_link_libraries(rl-test PRIVATE PkgConfig::readline)
```

```C
#include <iostream>

#include <readline/readline.h>
#include <readline/history.h>

int main()
{
  using_history();

  auto* line = readline("prompt *");

  std::cout << line <<  std::endl;

  free(line);

  return 0;
}
```

The library itself is taken from vcpkg, but the same problem also exist when building this from source.

The problem seems to stem from the fact that the library thinks that its compiled without varargs support.  This causes
```
rl_message(char* format, ...)
```
to get instead defined as
```
rl_message(char* format, int arg1, int arg2)
```

This causes a problem as `rl_display_search()` calls `rl_message("%s", <some char pointer>)` and the char pointer gets truncated to 32bits, which causes the crash.

The reason that it thinks that varargs are not available is because msvc by default does not define `__STDC__`.  Would it be possible to maybe remove this check from config.in.h ? i.e.
```diff
-#if defined (__STDC__) && defined (HAVE_STDARG_H)
+#if defined (HAVE_STDARG_H)
```
or something along these lines ?
```diff
 #if defined (__STDC__) && defined (HAVE_STDARG_H)
 #  define PREFER_STDARG
 #  define USE_VARARGS
 #else
 #  if defined (HAVE_VARARGS_H)
 #    define PREFER_VARARGS
 #    define USE_VARARGS
+#  else
+#    #if defined(HAVE_STDARG_H)
+#      define USE_VARARGS
+#      define PREFER_STDARG
+#    #endif
 #  endif
 #endif
```

**Comment by xiaozhuai** [comment]
@sebsura Thank you for reporting this issue. Would you please try the following changes?  If it works, I will submit a pr to vcpkg to fix it soon.
```diff
diff --git a/config.h b/config.h
index 39ba4a5..9070d4b 100644
--- a/config.h
+++ b/config.h
@@ -47,7 +47,7 @@
 #  define HAVE_STRCOLL 1
 #endif
 
-#if defined (__STDC__) && defined (HAVE_STDARG_H)
+#if (defined (__STDC__) || defined (_MSC_VER)) && defined (HAVE_STDARG_H)
 #  define PREFER_STDARG
 #  define USE_VARARGS
 #else

```

**Comment by xiaozhuai** [comment]
If you are using vcpkg, you can try the following quick fix. 
1. Save following two patch file
2. `cd /path/to/vcpkg && git apply vcpkg.patch`
3. Drop `fix_msvc_varargs.patch` to `/path/to/vcpkg/ports/readline-win32/`
4. Reinstall `readline-win32` and rebuild your user project.

Feel free to ask any question.

`vcpkg.patch`
```diff
diff --git a/ports/readline-win32/portfile.cmake b/ports/readline-win32/portfile.cmake
index 45fd95691..a5c340c23 100644
--- a/ports/readline-win32/portfile.cmake
+++ b/ports/readline-win32/portfile.cmake
@@ -4,6 +4,8 @@ vcpkg_from_github(
     REF 2b94fbb51f5da90b7bbd9b236da80be6f798e014
     SHA512 1285625ca6c608b98d13a783dd34461782bd88026bc09e6c9e70fd343e28561d1d7e5392b8068e52e93308029544276bdbc8ca12703c8976836561777a03dc17
     HEAD_REF master
+    PATCHES
+        fix_msvc_varargs.patch
 )
 
 vcpkg_cmake_configure(

```

`fix_msvc_varargs.patch`
```diff
diff --git a/config.h b/config.h
index 39ba4a5..9070d4b 100644
--- a/config.h
+++ b/config.h
@@ -47,7 +47,7 @@
 #  define HAVE_STRCOLL 1
 #endif
 
-#if defined (__STDC__) && defined (HAVE_STDARG_H)
+#if (defined (__STDC__) || defined (_MSC_VER)) && defined (HAVE_STDARG_H)
 #  define PREFER_STDARG
 #  define USE_VARARGS
 #else

```

**Comment by sebsura** [comment]
Thanks for the quick reply.  The fix you supplied worked perfectly!

**Comment by xiaozhuai** [comment]
@sebsura Ok, I will submit a pr to vcpkg soon. And this issue won't be closed until vcpkg accept our pr : )

**Comment by xiaozhuai** [comment]
@sebsura You can wait for https://github.com/microsoft/vcpkg/pull/41750 to be merged and then roll back the fix mentioned in https://github.com/xiaozhuai/readline-win32/issues/1#issuecomment-2434841904

**Comment by sebsura** [comment]
Great! Thanks for your work!

**Comment by xiaozhuai** [comment]
Done
